GET http://localhost:5000/api/goals
 
###
// below GET one
GET http://localhost:5000/api/goals/1234

###


###
POST http://localhost:5000/api/goals
Content-Type: application/json

{
   "text" : "This is a text body2"
     
}


###

DELETE  http://localhost:5000/api/goals/1234
###
PUT http://localhost:5000/api/goals/63b70b0a45fb603dce8bd1ce
Content-Type: application/json

{
    "text": "This does not exist..."
 

}




